// scripts/setup-sass.js
const fs = require('fs').promises; // Use promises for async handling
const path = require('path');

const baseDir = process.cwd(); // Use the current working directory (project root)
const sassDir = path.join(baseDir, 'sass');
const folders = [
  'abstracts',
  'base',
  'components',
  'layouts',
  'pages',
  'themes',
  'vendors'
];
const files = {
  // abstracts/
  'abstracts/_variables.scss': '/*\nItems categorized here: Global values like colors, fonts, or spacing that are used across the project but don\'t create CSS rules themselves. \nFor example, a color variable used in buttons and headers would go here to avoid repetition. \nThis folder keeps all the basic settings in one place so you can change them easily without looking through many files. \nIt makes the code easier to manage and update later. \nYou can add more variables as your project grows, like for shadows or z-indexes.\n*/\n$primary-color: #3498db;\n$secondary-color: #2ecc71;\n$font-stack: Arial, sans-serif;\n$spacing-unit: 16px;\n$border-radius: 5px;\n$transition-speed: 0.3s;\n',
  'abstracts/_mixins.scss': '/*\nItems categorized here: Reusable style patterns, such as flexbox setups or media queries, that can be included in other files. \nFor example, a mixin for responsive design would be here if it\'s used in multiple components. \nMixins are like shortcuts that let you write less code and keep things consistent. \nThey can take arguments to make them flexible for different situations. \nThis helps when you have similar styles in many places.\n*/\n@mixin flex-center {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}\n@mixin media-query($width) {\n  @media (min-width: $width) {\n    @content;\n  }\n}\n@mixin transition($property: all) {\n  transition: $property 0.3s ease;\n}\n@mixin box-shadow($level: 1) {\n  @if $level == 1 {\n    box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n  } @else if $level == 2 {\n    box-shadow: 0 4px 8px rgba(0,0,0,0.2);\n  }\n}\n',
  'abstracts/_functions.scss': '/*\nItems categorized here: Custom calculations, like color manipulation or math helpers. \nFor example, a function to calculate rem units would go here for use in sizing. \nFunctions return values that you can use in your styles. \nThey are good for complex math or logic that you want to reuse. \nThis folder is for things that help you compute values on the fly.\n*/\n@function rem($px) {\n  @return ($px / 16px) * 1rem;\n}\n@function darken($color, $amount) {\n  @return mix(black, $color, $amount);\n}\n@function lighten($color, $amount) {\n  @return mix(white, $color, $amount);\n}\n@function strip-unit($value) {\n  @return $value / ($value * 0 + 1);\n}\n@function em($px, $base: 16px) {\n  @return ($px / $base) * 1em;\n}\n@function vw($px, $viewport: 1920px) {\n  @return ($px / $viewport) * 100vw;\n}\n@function vh($px, $viewport: 1080px) {\n  @return ($px / $viewport) * 100vh;\n}\n@function random-color() {\n  @return rgb(random(255), random(255), random(255));\n}\n',
  // base/
  'base/_reset.scss': '/*\nItems categorized here: Global resets or normalizations that apply to all elements, like removing margins or setting box-sizing. \nFor example, a rule to reset list styles would go here because it\'s foundational and not specific to a component. \nThis file makes sure that browsers show your site the same way by clearing default styles. \nIt is like starting with a clean page.\n*/\n* {\n  margin: 0;\n  padding: 0;\n  box-sizing: border-box;\n}\nhtml {\n  line-height: 1.15;\n}\nul, ol {\n  list-style: none;\n}\nimg {\n  max-width: 100%;\n  height: auto;\n}\nblockquote {\n  quotes: none;\n}\n',
  'base/_typography.scss': '/*\nItems categorized here: Site-wide text styles, such as font families or heading sizes. \nFor example, defining the base font size for the body tag would be here, as it\'s not tied to a particular page or component. \nThis file sets the look of text for the whole site, making sure fonts and sizes are consistent. \nIt helps with reading and looks.\n*/\n body {\n  font-family: Arial, sans-serif;\n  font-size: 16px;\n  line-height: 1.5;\n  color: #333;\n}\nh1 {\n  font-size: 2.5rem;\n  margin-bottom: 1rem;\n}\nh2 {\n  font-size: 2rem;\n  margin-bottom: 0.75rem;\n}\nh3 {\n  font-size: 1.75rem;\n}\nh4 {\n  font-size: 1.5rem;\n}\nh5 {\n  font-size: 1.25rem;\n}\nh6 {\n  font-size: 1rem;\n}\np {\n  margin-bottom: 1em;\n}\na {\n  color: #3498db;\n  text-decoration: none;\n}\nstrong {\n  font-weight: bold;\n}\nem {\n  font-style: italic;\n}\n',
  'base/_elements.scss': '/*\nItems categorized here: Default styles for HTML elements like links, images, or tables. \nFor example, setting image max-width to 100% would go here for global application. \nThis file gives basic looks to common tags so they fit the site design from the start. \nIt saves time by setting defaults.\n*/\n a {\n  text-decoration: none;\n  color: inherit;\n}\nimg {\n  max-width: 100%;\n  height: auto;\n  display: block;\n}\ntable {\n  border-collapse: collapse;\n  width: 100%;\n}\nth, td {\n  border: 1px solid #ccc;\n  padding: 8px;\n}\ntr:nth-child(even) {\n  background-color: #f2f2f2;\n}\nblockquote {\n  border-left: 5px solid #eee;\n  padding-left: 15px;\n  font-style: italic;\n  margin: 1em 0;\n}\ncode {\n  background: #f4f4f4;\n  padding: 2px 4px;\n  border-radius: 3px;\n}\npre {\n  background: #f4f4f4;\n  padding: 10px;\n  overflow: auto;\n}\n',
  // components/
  'components/_button.scss': '/*\nItems categorized here: Self-contained UI elements that can be reused, like buttons or icons. \nFor example, a styled button class would go here because it\'s a modular piece that appears on multiple pages. \nThis file defines buttons that can be used anywhere, with different types like primary or secondary. \nIt keeps button styles in one place for easy changes.\n*/\n.button {\n  padding: 10px 20px;\n  background-color: #3498db;\n  color: white;\n  border: none;\n  cursor: pointer;\n  border-radius: 5px;\n  font-weight: bold;\n}\n.button:hover {\n  opacity: 0.9;\n}\n.button:disabled {\n  background-color: #ccc;\n  cursor: not-allowed;\n}\n.button-primary {\n  background-color: #3498db;\n}\n.button-secondary {\n  background-color: #2ecc71;\n}\n',
  'components/_card.scss': '/*\nItems categorized here: Independent blocks of content, such as product cards or alerts. \nFor example, a card with image and text would be here if it\'s reused in lists or grids. \nThis file sets up cards that can hold different content, like titles and images, and be used in many parts of the site. \nIt makes sure cards look the same everywhere.\n*/\n.card {\n  border: 1px solid #ccc;\n  padding: 20px;\n  border-radius: 5px;\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n  background: white;\n}\n.card-title {\n  font-weight: bold;\n  margin-bottom: 10px;\n}\n.card-content {\n  font-size: 14px;\n}\n.card-image {\n  width: 100%;\n  height: auto;\n  border-bottom: 1px solid #eee;\n}\n.card-footer {\n  margin-top: 15px;\n  text-align: right;\n}\n',
  'components/_form.scss': '/*\nItems categorized here: Form elements like inputs, labels, or selects. \nFor example, a styled input field would go here as it\'s a reusable component in multiple forms. \nThis file styles forms so they look good and are easy to use, with things like labels and buttons. \nIt can be used for login or contact forms.\n*/\n.form-group {\n  margin-bottom: 15px;\n}\nlabel {\n  display: block;\n  margin-bottom: 5px;\n  font-weight: bold;\n}\n.form-input {\n  padding: 10px;\n  border: 1px solid #ccc;\n  border-radius: 4px;\n  width: 100%;\n}\n.form-select {\n  width: 100%;\n  padding: 10px;\n  border: 1px solid #ccc;\n}\n.form-checkbox {\n  margin-right: 5px;\n}\n.form-radio {\n  margin-right: 5px;\n}\n.form-textarea {\n  width: 100%;\n  height: 100px;\n  padding: 10px;\n  border: 1px solid #ccc;\n}\n',
  'components/_modal.scss': '/*\nItems categorized here: Pop-up dialogs or overlays. \nFor example, a modal window for alerts would go here as a reusable UI component. \nThis file defines modals that can show messages or forms, with close buttons and overlays. \nIt is used for things like confirmation boxes.\n*/\n.modal {\n  position: fixed;\n  top: 50%;\n  left: 50%;\n  transform: translate(-50%, -50%);\n  background: white;\n  padding: 20px;\n  box-shadow: 0 4px 8px rgba(0,0,0,0.2);\n  z-index: 1000;\n}\n.modal-close {\n  position: absolute;\n  top: 10px;\n  right: 10px;\n  cursor: pointer;\n  font-size: 20px;\n}\n.modal-title {\n  margin-bottom: 15px;\n}\n.modal-body {\n  margin-bottom: 15px;\n}\n.modal-footer {\n  text-align: right;\n}\n',
  'components/_accordion.scss': '/*\nItems categorized here: Expandable sections. \nFor example, an accordion for FAQs would be here if reused. \nThis file sets up accordions that can open and close to show content, like questions and answers. \nIt is good for saving space on the page.\n*/\n.accordion-item {\n  border-bottom: 1px solid #ccc;\n}\n.accordion-title {\n  cursor: pointer;\n  padding: 10px;\n  background: #f4f4f4;\n}\n.accordion-content {\n  display: none;\n  padding: 10px;\n}\n.accordion-item.active .accordion-content {\n  display: block;\n}\n.accordion-item.active .accordion-title {\n  background: #e0e0e0;\n}\n',
  'components/_tabs.scss': '/*\nItems categorized here: Tabbed interfaces. \nFor example, tabs for switching content would go here. \nThis file creates tabs that let users switch between different views, like details and reviews. \nIt is useful for organizing information on one page.\n*/\n.tabs {\n  display: flex;\n  border-bottom: 1px solid #ccc;\n}\n.tab-item {\n  padding: 10px 20px;\n  cursor: pointer;\n}\n.tab-content {\n  display: none;\n  padding: 20px;\n}\n.tab-item.active {\n  background: #3498db;\n  color: white;\n  border-bottom: 2px solid #3498db;\n}\n.tab-content.active {\n  display: block;\n}\n',
  'components/_tooltip.scss': '/*\nItems categorized here: Hover tips. \nFor example, a tooltip on icons would go here. \nThis file makes tooltips that show extra information when you hover over something, like a question mark. \nIt helps explain things without taking space.\n*/\n.tooltip {\n  position: relative;\n  display: inline-block;\n}\n.tooltip-text {\n  visibility: hidden;\n  background: #333;\n  color: white;\n  padding: 5px 10px;\n  position: absolute;\n  bottom: 125%;\n  left: 50%;\n  transform: translateX(-50%);\n  white-space: nowrap;\n}\n.tooltip:hover .tooltip-text {\n  visibility: visible;\n}\n.tooltip-text::after {\n  content: " ";\n  position: absolute;\n  top: 100%;\n  left: 50%;\n  margin-left: -5px;\n  border-width: 5px;\n  border-style: solid;\n  border-color: #333 transparent transparent transparent;\n}\n',
  'components/_navbar.scss': '/*\nItems categorized here: Navigation bars. \nFor example, a responsive navbar would go here. \nThis file styles navigation bars that have links to other pages, with options for mobile views. \nIt is used at the top of the site.\n*/\n.navbar {\n  display: flex;\n  justify-content: space-between;\n  padding: 10px;\n}\n.navbar-links {\n  list-style: none;\n  display: flex;\n}\n.navbar-link {\n  margin-left: 20px;\n}\n@media (max-width: 768px) {\n  .navbar-links {\n    flex-direction: column;\n  }\n}\n',
  'components/_alert.scss': '/*\nItems categorized here: Notification messages. \nFor example, success or error alerts would go here. \nThis file defines alerts that show messages like "success" or "error", with colors to match. \nIt is used to give feedback to users.\n*/\n.alert {\n  padding: 15px;\n  margin-bottom: 20px;\n  border-radius: 4px;\n}\n.alert-success {\n  background: #dff0d8;\n  color: #3c763d;\n}\n.alert-error {\n  background: #f2dede;\n  color: #a94442;\n}\n.alert-info {\n  background: #d9edf7;\n  color: #31708f;\n}\n.alert-warning {\n  background: #fcf8e3;\n  color: #8a6d3b;\n}\n.alert-close {\n  float: right;\n  cursor: pointer;\n}\n',
  'components/_breadcrumb.scss': '/*\nItems categorized here: Navigation paths. \nFor example, a breadcrumb trail would go here. \nThis file creates breadcrumbs that show the path like "home > page", to help users know where they are. \nIt is good for deep sites.\n*/\n.breadcrumb {\n  list-style: none;\n  display: flex;\n  padding: 0;\n}\n.breadcrumb-item {\n  margin-right: 5px;\n}\n.breadcrumb-item::after {\n  content: " / ";\n}\n.breadcrumb-item:last-child::after {\n  content: "";\n}\n.breadcrumb-item a {\n  color: #3498db;\n}\n',
  'components/_pagination.scss': '/*\nItems categorized here: Page navigation links. \nFor example, numbered pages would go here. \nThis file sets up pagination like "1 2 3", with links to other pages. \nIt is used for lists that have many items.\n*/\n.pagination {\n  display: flex;\n  list-style: none;\n  justify-content: center;\n}\n.page-item {\n  margin: 0 5px;\n}\n.page-link {\n  padding: 5px 10px;\n  border: 1px solid #ccc;\n  text-decoration: none;\n}\n.page-item.active .page-link {\n  background: #3498db;\n  color: white;\n}\n.page-item.disabled .page-link {\n  color: #ccc;\n}\n',
  'components/_progress-bar.scss': '/*\nItems categorized here: Loading indicators. \nFor example, a progress bar for uploads would go here. \nThis file makes progress bars that show how much is done, like 50%. \nIt is used for loading or tasks.\n*/\n.progress {\n  background: #eee;\n  height: 20px;\n  border-radius: 10px;\n  overflow: hidden;\n}\n.progress-bar {\n  background: #3498db;\n  height: 100%;\n  transition: width 0.3s;\n}\n.progress-text {\n  text-align: center;\n  color: white;\n  position: absolute;\n  width: 100%;\n  line-height: 20px;\n}\n',
  'components/_dropdown.scss': '/*\nItems categorized here: Dropdown menus. \nFor example, a select menu with options would go here. \nThis file styles dropdowns that show more choices when clicked, like a menu. \nIt is used for navigation or forms.\n*/\n.dropdown {\n  position: relative;\n}\n.dropdown-toggle {\n  padding: 10px;\n  background: #f4f4f4;\n  cursor: pointer;\n}\n.dropdown-menu {\n  display: none;\n  position: absolute;\n  background: white;\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n}\n.dropdown.active .dropdown-menu {\n  display: block;\n}\n.dropdown-item {\n  padding: 10px;\n  cursor: pointer;\n}\n.dropdown-item:hover {\n  background: #f0f0f0;\n}\n',
  'components/_badge.scss': '/*\nItems categorized here: Labels or tags. \nFor example, status badges would go here. \nThis file creates badges like "new" or "sale", with colors to stand out. \nIt is used to highlight small pieces of information.\n*/\n.badge {\n  padding: 5px 10px;\n  border-radius: 20px;\n  font-size: 12px;\n}\n.badge-success {\n  background: #2ecc71;\n  color: white;\n}\n.badge-warning {\n  background: #f39c12;\n  color: white;\n}\n.badge-error {\n  background: #e74c3c;\n  color: white;\n}\n.badge-info {\n  background: #3498db;\n  color: white;\n}\n.badge-count {\n  background: #e74c3c;\n  color: white;\n  position: absolute;\n  top: -5px;\n  right: -5px;\n}\n',
  'components/_carousel.scss': '/*\nItems categorized here: Image sliders. \nFor example, a rotating carousel would go here. \nThis file sets up carousels that slide through images or content, with arrows and dots. \nIt is used for galleries or features.\n*/\n.carousel {\n  position: relative;\n  overflow: hidden;\n}\n.carousel-slide {\n  display: none;\n}\n.carousel-slide.active {\n  display: block;\n}\n.carousel-next, .carousel-prev {\n  position: absolute;\n  top: 50%;\n  cursor: pointer;\n}\n.carousel-dots {\n  text-align: center;\n}\n.carousel-dot {\n  display: inline-block;\n  width: 10px;\n  height: 10px;\n  background: #ccc;\n  border-radius: 50%;\n  margin: 5px;\n}\n.carousel-dot.active {\n  background: #3498db;\n}\n',
  'components/_icon.scss': '/*\nItems categorized here: Icon styles. \nFor example, SVG icons or font icons would go here. \nThis file styles icons that can be used in buttons or menus. \nIt is used to add small pictures or symbols.\n*/\n.icon {\n  font-size: 24px;\n  color: #3498db;\n}\n.icon-small {\n  font-size: 16px;\n}\n.icon-large {\n  font-size: 32px;\n}\n.icon-success {\n  color: #2ecc71;\n}\n.icon-error {\n  color: #e74c3c;\n}\n',
  'components/_list.scss': '/*\nItems categorized here: Styled lists. \nFor example, bullet points or numbered lists would go here. \nThis file creates lists that can be used for menus or items, with hover effects. \nIt is used to show groups of things.\n*/\n.list {\n  list-style: none;\n}\n.list-item {\n  padding: 10px;\n  border-bottom: 1px solid #eee;\n}\n.list-item:hover {\n  background: #f0f0f0;\n}\n.list-check {\n  list-style-type: check;\n}\n.list-number {\n  list-style-type: decimal;\n}\n',
  'components/_table.scss': '/*\nItems categorized here: Data tables. \nFor example, responsive tables would go here. \nThis file styles tables for data, with stripes and hover. \nIt is used for showing information in rows and columns.\n*/\n.table {\n  width: 100%;\n  border-collapse: collapse;\n}\n.table th, .table td {\n  border: 1px solid #ccc;\n  padding: 10px;\n}\n.table thead {\n  background: #f4f4f4;\n}\n.table-striped tr:nth-child(even) {\n  background: #f9f9f9;\n}\n.table-hover tr:hover {\n  background: #f0f0f0;\n}\n',
  // layouts/
  'layouts/_header.scss': '/*\nItems categorized here: Major structural elements that define the page layout, like headers or sidebars. \nFor example, a navigation bar that spans the top of the site would go here, as it\'s about positioning rather than specific content. \nThis file sets the layout for the top part of the page, with logo and menu.\n*/\n.header {\n  display: flex;\n  justify-content: space-between;\n  padding: 20px;\n  background-color: #f8f8f8;\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n}\n.logo {\n  font-size: 24px;\n  font-weight: bold;\n}\n.nav-menu {\n  display: flex;\n  list-style: none;\n}\n.nav-item {\n  margin-left: 20px;\n}\n.search-bar {\n  padding: 5px;\n  border: 1px solid #ccc;\n}\n',
  'layouts/_footer.scss': '/*\nItems categorized here: Bottom sections or copyright areas. \nFor example, a footer with links and social icons would be here as it\'s a layout element shared across pages. \nThis file styles the bottom of the page, with links and copyright.\n*/\n.footer {\n  text-align: center;\n  padding: 10px;\n  background-color: #333;\n  color: white;\n  margin-top: 20px;\n}\n.footer-links {\n  list-style: none;\n  display: flex;\n  justify-content: center;\n}\n.footer-link {\n  margin: 0 10px;\n  color: white;\n}\n.social-icons {\n  margin-top: 10px;\n}\n.copyright {\n  font-size: 12px;\n}\n',
  'layouts/_grid.scss': '/*\nItems categorized here: Systems for arranging content, such as columns or flexbox grids. \nFor example, a 12-column grid system would be categorized here because it\'s a layout tool used across pages. \nThis file provides classes for grid layouts, with columns for different sizes.\n*/\n.grid {\n  display: grid;\n  grid-template-columns: repeat(12, 1fr);\n  gap: 20px;\n}\n.col-1 {\n  grid-column: span 1;\n}\n.col-2 {\n  grid-column: span 2;\n}\n.col-3 {\n  grid-column: span 3;\n}\n.col-4 {\n  grid-column: span 4;\n}\n.col-5 {\n  grid-column: span 5;\n}\n.col-6 {\n  grid-column: span 6;\n}\n.col-7 {\n  grid-column: span 7;\n}\n.col-8 {\n  grid-column: span 8;\n}\n.col-9 {\n  grid-column: span 9;\n}\n.col-10 {\n  grid-column: span 10;\n}\n.col-11 {\n  grid-column: span 11;\n}\n.col-12 {\n  grid-column: span 12;\n}\n@media (max-width: 768px) {\n  .grid {\n    grid-template-columns: 1fr;\n  }\n}\n',
  'layouts/_sidebar.scss': '/*\nItems categorized here: Side panels or navigation bars. \nFor example, a left sidebar for menus would go here. \nThis file styles sidebars that can hold links or widgets, with options for width and color.\n*/\n.sidebar {\n  width: 200px;\n  float: left;\n  padding: 20px;\n  background: #f0f0f0;\n  height: 100vh;\n}\n.sidebar-item {\n  margin-bottom: 10px;\n}\n.sidebar-title {\n  font-weight: bold;\n}\n.content {\n  margin-left: 220px;\n  padding: 20px;\n}\n@media (max-width: 768px) {\n  .sidebar {\n    width: 100%;\n    height: auto;\n  }\n  .content {\n    margin-left: 0;\n  }\n}\n',
  'layouts/_container.scss': '/*\nItems categorized here: Wrappers for content width. \nFor example, a max-width container for centering. \nThis file provides classes for containers that limit width and center content, with different sizes.\n*/\n.container {\n  max-width: 1200px;\n  margin: 0 auto;\n  padding: 0 20px;\n}\n.container-fluid {\n  width: 100%;\n  padding: 0 20px;\n}\n.container-small {\n  max-width: 800px;\n  margin: 0 auto;\n}\n.container-large {\n  max-width: 1400px;\n  margin: 0 auto;\n}\n.container-flex {\n  display: flex;\n  flex-wrap: wrap;\n}\n',
  'layouts/_hero.scss': '/*\nItems categorized here: Full-width banner sections. \nFor example, a hero layout with background image would go here. \nThis file styles hero areas that are big and eye-catching, with text and buttons.\n*/\n.hero {\n  height: 400px;\n  background-size: cover;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  position: relative;\n}\n.hero-text {\n  text-align: center;\n  color: white;\n  font-size: 2rem;\n  z-index: 1;\n}\n.hero-overlay {\n  position: absolute;\n  top: 0;\n  left: 0;\n  width: 100%;\n  height: 100%;\n  background: rgba(0,0,0,0.5);\n}\n.hero-button {\n  margin-top: 20px;\n  padding: 10px 20px;\n  background: white;\n  color: black;\n}\n',
  'layouts/_section.scss': '/*\nItems categorized here: General section wrappers. \nFor example, padded sections for content blocks. \nThis file creates sections that divide the page, with padding and colors.\n*/\n.section {\n  padding: 50px 0;\n}\n.section-title {\n  text-align: center;\n  margin-bottom: 30px;\n  font-size: 2rem;\n}\n.section-content {\n  max-width: 1000px;\n  margin: 0 auto;\n}\n.section-alternate {\n  background: #f9f9f9;\n}\n.section-dark {\n  background: #333;\n  color: white;\n}\n.section-image {\n  background-size: cover;\n  height: 300px;\n}\n',
  'layouts/_flex-layout.scss': '/*\nItems categorized here: Flexible box layouts. \nFor example, a flex container for rows would go here. \nThis file provides classes for flex layouts, with options for direction and wrap.\n*/\n.flex-layout {\n  display: flex;\n  flex-wrap: wrap;\n}\n.flex-item {\n  flex: 1;\n  padding: 10px;\n}\n.flex-reverse {\n  flex-direction: row-reverse;\n}\n@media (max-width: 768px) {\n  .flex-layout {\n    flex-direction: column;\n  }\n}\n',
  'layouts/_main-content.scss': '/*\nItems categorized here: Main content areas. \nFor example, a wrapper for page content would go here. \nThis file styles the main part of the page, with margins and colors.\n*/\n.main-content {\n  padding: 20px;\n  background: white;\n}\n.main-title {\n  margin-bottom: 20px;\n}\n.main-sidebar {\n  width: 30%;\n}\n.main-body {\n  width: 70%;\n}\n@media (max-width: 992px) {\n  .main-sidebar, .main-body {\n    width: 100%;\n  }\n}\n',
  'layouts/_columns.scss': '/*\nItems categorized here: Multi-column layouts. \nFor example, two-column designs would go here. \nThis file sets up columns for content, with widths and floats.\n*/\n.columns {\n  display: flex;\n}\n.column {\n  flex: 1;\n  padding: 20px;\n}\n.column-left {\n  width: 40%;\n}\n.column-right {\n  width: 60%;\n}\n@media (max-width: 768px) {\n  .columns {\n    flex-direction: column;\n  }\n}\n',
  'layouts/_wrapper.scss': '/*\nItems categorized here: General wrappers for sections. \nFor example, a full-width wrapper would go here. \nThis file creates wrappers that contain other elements, with max widths.\n*/\n.wrapper {\n  max-width: 1400px;\n  margin: 0 auto;\n}\n.wrapper-padded {\n  padding: 20px;\n}\n.wrapper-bordered {\n  border: 1px solid #ccc;\n}\n.wrapper-shadow {\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n}\n.wrapper-flex {\n  display: flex;\n}\n',
  // pages/
  'pages/_home.scss': '/*\nItems categorized here: Styles unique to one page, like hero sections or custom layouts for that page only. \nFor example, a full-width banner on the home page would go here, as it\'s not reused elsewhere. \nThis file has styles just for the home page, like special sections or arrangements.\n*/\n.home-hero {\n  background-image: url(\'../images/hero.jpg\');\n  height: 400px;\n  text-align: center;\n  color: white;\n  padding-top: 150px;\n}\n.home-content {\n  margin-top: 40px;\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 20px;\n}\n.home-feature {\n  padding: 20px;\n  background: #f9f9f9;\n  text-align: center;\n}\n.home-cta {\n  text-align: center;\n  margin-top: 50px;\n}\n.home-slider {\n  margin-top: 30px;\n}\n.home-testimonials {\n  display: flex;\n  gap: 20px;\n}\n.home-testimonial {\n  flex: 1;\n  padding: 20px;\n  background: #fff;\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n}\n',
  'pages/_about.scss': '/*\nItems categorized here: Page-specific overrides or unique elements. \nFor example, a team section with profiles on the about page would be here if it\'s only on that page. \nThis file has styles just for the about page, like team lists or history timelines.\n*/\n.about-section {\n  padding: 50px;\n  background: #f0f0f0;\n  text-align: center;\n}\n.team {\n  display: flex;\n  justify-content: space-around;\n  flex-wrap: wrap;\n}\n.team-member {\n  width: 30%;\n  margin: 20px;\n  background: white;\n  padding: 15px;\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n}\n.team-photo {\n  border-radius: 50%;\n  width: 100px;\n  height: 100px;\n}\n.team-name {\n  font-weight: bold;\n}\n.team-role {\n  font-style: italic;\n}\n.about-history {\n  margin-top: 40px;\n}\n.about-mission {\n  margin-top: 40px;\n  font-size: 18px;\n}\n',
  'pages/_contact.scss': '/*\nItems categorized here: Contact form or map styles specific to the contact page. \nFor example, a map embed with custom borders would go here. \nThis file has styles just for the contact page, like forms and info boxes.\n*/\n.contact-form {\n  max-width: 600px;\n  margin: 0 auto;\n  padding: 20px;\n  background: #fff;\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n}\n.contact-map {\n  height: 300px;\n  margin-top: 20px;\n  border: 1px solid #ccc;\n}\n.contact-info {\n  margin-top: 40px;\n  text-align: center;\n}\n.contact-address {\n  margin-bottom: 10px;\n}\n.contact-phone {\n  margin-bottom: 10px;\n}\n.contact-email {\n  margin-bottom: 10px;\n}\n.contact-hours {\n  margin-top: 20px;\n}\n',
  'pages/_blog.scss': '/*\nItems categorized here: Blog list or post styles unique to blog pages. \nFor example, article previews would go here. \nThis file has styles just for the blog page, like post lists and sidebars.\n*/\n.blog-list {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n  gap: 20px;\n}\n.blog-post {\n  border: 1px solid #eee;\n  padding: 15px;\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n}\n.blog-title {\n  font-size: 1.5rem;\n  margin-bottom: 10px;\n}\n.blog-excerpt {\n  font-size: 14px;\n}\n.blog-date {\n  color: #999;\n  font-size: 12px;\n}\n.blog-tags {\n  margin-top: 10px;\n}\n.blog-sidebar {\n  width: 30%;\n}\n.blog-main {\n  width: 70%;\n}\n',
  'pages/_product.scss': '/*\nItems categorized here: Product detail styles for e-commerce pages. \nFor example, image galleries on product pages would go here. \nThis file has styles just for the product page, like images and prices.\n*/\n.product-detail {\n  display: flex;\n  gap: 30px;\n}\n.product-image {\n  width: 50%;\n  height: auto;\n}\n.product-info {\n  width: 50%;\n}\n.product-title {\n  font-size: 2rem;\n}\n.product-price {\n  font-size: 1.5rem;\n  color: #e74c3c;\n}\n.product-description {\n  margin-top: 20px;\n}\n.product-add-to-cart {\n  margin-top: 20px;\n  padding: 10px 20px;\n  background: #3498db;\n  color: white;\n}\n.product-reviews {\n  margin-top: 40px;\n}\n',
  'pages/_login.scss': '/*\nItems categorized here: Login form styles specific to the login page. \nFor example, a centered form with inputs would go here. \nThis file has styles just for the login page, like forms and links.\n*/\n.login-form {\n  max-width: 400px;\n  margin: 100px auto;\n  padding: 20px;\n  background: #fff;\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n}\n.login-title {\n  text-align: center;\n}\n.login-button {\n  width: 100%;\n}\n.login-forgot {\n  text-align: right;\n  margin-top: 10px;\n}\n',
  'pages/_dashboard.scss': '/*\nItems categorized here: User dashboard layouts. \nFor example, panels with stats would go here. \nThis file has styles just for the dashboard page, like charts and stats.\n*/\n.dashboard {\n  display: grid;\n  grid-template-columns: repeat(4, 1fr);\n  gap: 20px;\n}\n.dashboard-panel {\n  padding: 20px;\n  background: #f9f9f9;\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n}\n.dashboard-title {\n  margin-bottom: 10px;\n}\n.dashboard-stats {\n  font-size: 2rem;\n}\n.dashboard-chart {\n  margin-top: 20px;\n}\n.dashboard-recent {\n  margin-top: 20px;\n}\n.dashboard-link {\n  color: #2ecc71;\n}\n',
  'pages/_profile.scss': '/*\nItems categorized here: User profile views. \nFor example, avatar and bio sections would go here. \nThis file has styles just for the profile page, like images and info.\n*/\n.profile {\n  max-width: 800px;\n  margin: 0 auto;\n  padding: 20px;\n}\n.profile-avatar {\n  width: 150px;\n  height: 150px;\n  border-radius: 50%;\n}\n.profile-bio {\n  margin-top: 20px;\n}\n.profile-edit {\n  margin-top: 20px;\n  padding: 10px 20px;\n  background: #3498db;\n  color: white;\n}\n.profile-stats {\n  display: flex;\n  gap: 20px;\n}\n.profile-stat {\n  text-align: center;\n}\n',
  'pages/_search.scss': '/*\nItems categorized here: Search result layouts. \nFor example, result lists would go here. \nThis file has styles just for the search page, like forms and results.\n*/\n.search-form {\n  max-width: 600px;\n  margin: 20px auto;\n}\n.search-results {\n  display: grid;\n  gap: 20px;\n}\n.search-item {\n  padding: 15px;\n  border: 1px solid #eee;\n}\n.search-title {\n  font-weight: bold;\n}\n.search-excerpt {\n  color: #666;\n}\n.search-no-results {\n  text-align: center;\n  color: #999;\n}\n',
  'pages/_faq.scss': '/*\nItems categorized here: FAQ accordion styles. \nFor example, question-answer pairs would go here. \nThis file has styles just for the FAQ page, like accordions and searches.\n*/\n.faq-item {\n  margin-bottom: 20px;\n}\n.faq-question {\n  font-weight: bold;\n  cursor: pointer;\n}\n.faq-answer {\n  margin-top: 10px;\n  color: #666;\n}\n.faq-search {\n  margin-bottom: 30px;\n}\n.faq-categories {\n  display: flex;\n  gap: 20px;\n}\n',
  'pages/_pricing.scss': '/*\nItems categorized here: Pricing table styles. \nFor example, plan comparisons would go here. \nThis file has styles just for the pricing page, like tables and buttons.\n*/\n.pricing {\n  display: flex;\n  gap: 20px;\n}\n.pricing-plan {\n  flex: 1;\n  padding: 20px;\n  border: 1px solid #ccc;\n}\n.pricing-title {\n  text-align: center;\n}\n.pricing-price {\n  font-size: 2rem;\n  text-align: center;\n}\n.pricing-features {\n  list-style: none;\n}\n.pricing-button {\n  display: block;\n  text-align: center;\n}\n',
  'pages/_services.scss': '/*\nItems categorized here: Service list styles. \nFor example, service descriptions would go here. \nThis file has styles just for the services page, like icons and text.\n*/\n.services {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 20px;\n}\n.service-item {\n  text-align: center;\n  padding: 20px;\n  background: #f9f9f9;\n}\n.service-icon {\n  font-size: 40px;\n}\n.service-title {\n  margin-top: 10px;\n}\n.service-description {\n  margin-top: 10px;\n}\n',
  'pages/_portfolio.scss': '/*\nItems categorized here: Portfolio gallery styles. \nFor example, project showcases would go here. \nThis file has styles just for the portfolio page, like images and captions.\n*/\n.portfolio {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 20px;\n}\n.portfolio-item {\n  position: relative;\n}\n.portfolio-image {\n  width: 100%;\n}\n.portfolio-caption {\n  position: absolute;\n  bottom: 0;\n  background: rgba(0,0,0,0.5);\n  color: white;\n  width: 100%;\n  padding: 10px;\n}\n.portfolio-link {\n  color: white;\n}\n',
  'pages/_team.scss': '/*\nItems categorized here: Team member profiles. \nFor example, bios and photos would go here. \nThis file has styles just for the team page, like grids and cards.\n*/\n.team {\n  display: grid;\n  grid-template-columns: repeat(4, 1fr);\n  gap: 20px;\n}\n.team-member {\n  text-align: center;\n  padding: 20px;\n  background: #fff;\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n}\n.team-photo {\n  border-radius: 50%;\n  width: 150px;\n  height: 150px;\n}\n.team-name {\n  margin-top: 10px;\n}\n.team-role {\n  color: #666;\n}\n.team-bio {\n  margin-top: 10px;\n  font-size: 14px;\n}\n',
  'pages/_testimonials.scss': '/*\nItems categorized here: Customer review sections. \nFor example, quote blocks would go here. \nThis file has styles just for the testimonials page, like sliders or grids.\n*/\n.testimonials {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 20px;\n}\n.testimonial {\n  padding: 20px;\n  background: #f9f9f9;\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n}\n.testimonial-quote {\n  font-style: italic;\n}\n.testimonial-author {\n  margin-top: 10px;\n  text-align: right;\n}\n.testimonial-rating {\n  margin-top: 10px;\n  color: #f39c12;\n}\n',
  // themes/
  'themes/_theme-default.scss': '/*\nItems categorized here: Default visual settings, like color schemes. \nFor example, base colors for the site would go here if they define the overall theme. \nThis file sets the main look of the site, with variables for colors and fonts.\n*/\n:root {\n  --main-bg: #fff;\n  --main-text: #000;\n  --accent-color: #3498db;\n  --secondary-accent: #2ecc71;\n}\n',
  'themes/_theme-dark.scss': '/*\nItems categorized here: Variations in colors or styles for themes, like dark mode overrides. \nFor example, a set of variables for inverted colors would be here if they apply to the whole site under a theme switch. \nThis file changes the site to dark mode, with dark backgrounds and light text.\n*/\n:root {\n  --background: #333;\n  --text-color: #fff;\n  --accent-color: #2ecc71;\n  --secondary-accent: #e67e22;\n}\nbody {\n  background: var(--background);\n  color: var(--text-color);\n}\na {\n  color: var(--accent-color);\n}\n.button {\n  background: var(--accent-color);\n  color: var(--text-color);\n}\n',
  'themes/_theme-light.scss': '/*\nItems categorized here: Light mode or alternative themes. \nFor example, pastel colors for a light theme would be here. \nThis file sets a light look, with soft colors and white backgrounds.\n*/\n:root {\n  --background: #f9f9f9;\n  --text-color: #333;\n  --accent-color: #e67e22;\n  --secondary-accent: #9b59b6;\n}\nbody {\n  background: var(--background);\n  color: var(--text-color);\n}\n.button {\n  background: var(--accent-color);\n}\n.card {\n  background: var(--background);\n}\n',
  'themes/_theme-high-contrast.scss': '/*\nItems categorized here: Accessibility-focused themes. \nFor example, high-contrast colors for better readability would go here. \nThis file makes the site easy to read, with strong colors and lines.\n*/\n:root {\n  --background: #000;\n  --text-color: #fff;\n  --accent-color: #ff0;\n  --secondary-accent: #f0f;\n}\nbody {\n  background: var(--background);\n  color: var(--text-color);\n}\na {\n  color: var(--accent-color);\n  text-decoration: underline;\n}\ninput {\n  border: 2px solid #fff;\n  background: #000;\n  color: #fff;\n}\n.button {\n  background: #ff0;\n  color: #000;\n}\n',
  'themes/_theme-monochrome.scss': '/*\nItems categorized here: Black and white themes. \nFor example, grayscale colors would go here. \nThis file removes colors, making the site black and white.\n*/\n:root {\n  --background: #fff;\n  --text-color: #000;\n  --accent-color: #808080;\n}\n* {\n  filter: grayscale(100%);\n}\nbody {\n  background: var(--background);\n  color: var(--text-color);\n}\n.button {\n  background: var(--accent-color);\n  color: #fff;\n}\n',
  'themes/_theme-retro.scss': '/*\nItems categorized here: Retro-style themes. \nFor example, old-school colors would go here. \nThis file gives the site an old look, with simple colors and fonts.\n*/\n:root {\n  --background: #c0c0c0;\n  --text-color: #000;\n  --accent-color: #ff00ff;\n}\nbody {\n  font-family: "Courier New", monospace;\n}\n.button {\n  border: 2px solid #000;\n  background: #c0c0c0;\n}\n',
  'themes/_theme-vintage.scss': '/*\nItems categorized here: Vintage looks. \nFor example, sepia tones would go here. \nThis file adds a old photo look, with brown tones.\n*/\n:root {\n  --background: #f4e3c1;\n  --text-color: #5e3c12;\n  --accent-color: #8b4513;\n}\nbody {\n  filter: sepia(50%);\n}\na {\n  color: var(--accent-color);\n}\n',
  'themes/_theme-minimal.scss': '/*\nItems categorized here: Simple, clean themes. \nFor example, white space and basic colors would go here. \nThis file makes the site plain, with lots of space.\n*/\n:root {\n  --background: #fff;\n  --text-color: #333;\n  --accent-color: #000;\n}\nbody {\n  font-family: "Helvetica", sans-serif;\n}\n.button {\n  background: transparent;\n  border: 1px solid #000;\n  color: #000;\n}\n',
  'themes/_theme-colorful.scss': '/*\nItems categorized here: Bright, colorful themes. \nFor example, many colors for fun looks would go here. \nThis file adds lots of colors to the site.\n*/\n:root {\n  --background: #fff;\n  --text-color: #333;\n  --accent-color: #ff69b4;\n}\nbody {\n  background: linear-gradient(to right, #ff69b4, #3498db);\n}\n.button {\n  background: #ff69b4;\n}\n',
  // main.scss (the entry point)
  'main.scss': '// Items categorized here: Not applicable, as main.scss is the entry point. It doesn\'t contain styles but pulls in partials from other folders.\n@use \'abstracts/variables\';\n@use \'abstracts/mixins\';\n@use \'abstracts/functions\';\n@use \'base/reset\';\n@use \'base/typography\';\n@use \'base/elements\';\n@use \'components/button\';\n@use \'components/card\';\n@use \'components/form\';\n@use \'components/modal\';\n@use \'components/accordion\';\n@use \'components/tabs\';\n@use \'components/tooltip\';\n@use \'components/navbar\';\n@use \'components/alert\';\n@use \'components/breadcrumb\';\n@use \'components/pagination\';\n@use \'components/progress-bar\';\n@use \'components/dropdown\';\n@use \'components/badge\';\n@use \'components/carousel\';\n@use \'components/icon\';\n@use \'components/list\';\n@use \'components/table\';\n@use \'layouts/header\';\n@use \'layouts/footer\';\n@use \'layouts/grid\';\n@use \'layouts/sidebar\';\n@use \'layouts/container\';\n@use \'layouts/hero\';\n@use \'layouts/section\';\n@use \'layouts/flex-layout\';\n@use \'layouts/main-content\';\n@use \'layouts/columns\';\n@use \'layouts/wrapper\';\n@use \'pages/home\';\n@use \'pages/about\';\n@use \'pages/contact\';\n@use \'pages/blog\';\n@use \'pages/product\';\n@use \'pages/login\';\n@use \'pages/dashboard\';\n@use \'pages/profile\';\n@use \'pages/search\';\n@use \'pages/faq\';\n@use \'pages/pricing\';\n@use \'pages/services\';\n@use \'pages/portfolio\';\n@use \'pages/team\';\n@use \'pages/testimonials\';\n@use \'themes/theme-default\';\n@use \'themes/theme-dark\';\n@use \'themes/theme-light\';\n@use \'themes/theme-high-contrast\';\n@use \'themes/theme-monochrome\';\n@use \'themes/theme-retro\';\n@use \'themes/theme-vintage\';\n@use \'themes/theme-minimal\';\n@use \'themes/theme-colorful\';\n@use \'vendors/bootstrap\';\n@use \'vendors/font-awesome\';\n@use \'vendors/normalize\';\n@use \'vendors/swiper\';\n@use \'vendors/jquery-ui\';\n@use \'vendors/slick-carousel\';\n@use \'vendors/chart-js\';\n@use \'vendors/leaflet\';\n@use \'vendors/animate\';\n@use \'vendors/fullcalendar\';\n@use \'vendors/dropzone\';\n@use \'vendors/prism\';\n'
};

async function setupSass() {
  try {
    // Log paths for debugging
    console.log('Current working directory:', baseDir);
    console.log('Target Sass directory:', sassDir);

    // Create Sass directory if not exists
    await fs.mkdir(sassDir, { recursive: true });
    console.log('Sass directory created or already exists:', sassDir);

    // Create subfolders
    for (const folder of folders) {
      const folderPath = path.join(sassDir, folder);
      await fs.mkdir(folderPath, { recursive: true });
      console.log('Folder created or already exists:', folderPath);
    }

    // Create files
    for (const [filePath, content] of Object.entries(files)) {
      const fullPath = path.join(sassDir, filePath);
      await fs.writeFile(fullPath, content);
      console.log('File created or overwritten:', fullPath);
    }

    console.log('7-1 Sass structure successfully created in sass/');
  } catch (err) {
    console.error('Error setting up Sass structure:', err.message);
    process.exit(1); // Exit with error code
  }
}

setupSass();